export { default as AppSidebar }           from './AppSidebar.vue'
export { default as AppTopNav }            from './AppTopNav.vue'
export { default as ComingSoonView }       from './ComingSoonView.vue'
export { default as AbsenceRequestModal }  from './AbsenceRequestModal.vue'
export { default as OrgChartTree }         from './OrgChartTree.vue'
export { default as OrgChartView }         from './OrgChartView.vue'
// ── Coquilles de page partagées ──
export { default as ListPageLayout }       from './shared/ListPageLayout.vue'
// ── Primitives du design system (portées du frontdesk P247_FD_LWL_APP) ──
export { default as Button }               from './ui/button/Button.vue'
export { default as Card }                 from './ui/card/Card.vue'
export { default as CardHeader }           from './ui/card/CardHeader.vue'
export { default as CardTitle }            from './ui/card/CardTitle.vue'
export { default as CardDescription }      from './ui/card/CardDescription.vue'
export { default as CardContent }          from './ui/card/CardContent.vue'
export { default as Input }                from './ui/input/Input.vue'
export { default as FormInput }            from './ui/input/FormInput.vue'
export { default as Label }                from './ui/Label/Label.vue'
export { default as Alert }                from './ui/alert/Alert.vue'
export { default as AlertDescription }     from './ui/alert/AlertDescription.vue'
export { default as BaseFormField }        from './ui/form-field/BaseFormField.vue'
export { default as OptionsSelect }        from './ui/options-select/OptionsSelect.vue'

export { default as StatusPill }           from './ui/StatusPill.vue'
export { default as UserAvatar }           from './ui/UserAvatar.vue'
export { default as DataTable }            from './ui/DataTable.vue'
export { default as SearchableDropdown }   from './ui/SearchableDropdown.vue'
export { default as ForWhomSelector }      from './ui/ForWhomSelector.vue'
